packages:
  - packages/*
  - demo
  - demo-openid
  - samples/*

catalog:
  '@biomejs/biome': ^2.3.10
  '@animo-id/pex': ^6.1.1
  '@astronautlabs/jsonpath': ^1.1.2
  '@hyperledger/anoncreds-nodejs': ^0.3.4
  '@hyperledger/anoncreds-shared': ^0.3.4
  '@hyperledger/indy-vdr-nodejs': ^0.2.3
  '@hyperledger/indy-vdr-shared': ^0.2.3
  '@openwallet-foundation/askar-nodejs': ^0.4.3
  '@openwallet-foundation/askar-shared': ^0.4.3
  '@peculiar/x509': ^1.14.2
  '@sphereon/pex-models': ^2.3.2
  '@stablelib/ed25519': ^2.0.2
  '@types/express': ^5.0.6
  '@types/node': ^20.19.25
  '@types/ws': ^8.18.1
  '@vitest/coverage-v8': ^4.0.16
  class-transformer: 0.5.1
  # We have locked the version in a lot of repos because 0.14.2 released
  # some breaking changes. We now account for that, but keep it at ^0.14.1
  # for now to not make npm install multiple versions (as 0.14.1 is still valid)
  class-validator: ^0.14.1
  express: ^5.2.0
  nock: ^14.0.10
  reflect-metadata: 0.2.2
  rxjs: ^7.8.2
  tsyringe: ^4.10.0
  typescript: ~5.9.3
  vitest: ^4.0.16
  ws: ^8.18.3
  zod: ^4.1.12

ignoredBuiltDependencies:
  - es5-ext
  - esbuild
  - protobufjs
  - secp256k1

onlyBuiltDependencies:
  - '@2060.io/ffi-napi'
  - '@2060.io/ref-napi'
  - '@biomejs/biome'
  - '@hyperledger/anoncreds-nodejs'
  - '@hyperledger/indy-vdr-nodejs'
  - '@openwallet-foundation/askar-nodejs'
  - zstd-napi
  - cbor-extract
