packages:
  - packages/*
  - demo
  - demo-openid
  - samples/*

catalog:
  # NOTE: keep at 1.13 until https://github.com/PeculiarVentures/x509/pull/108 is merged and released
  "@peculiar/x509": ~1.13.0
  "@types/node": ^20.19.0
  tsyringe: ^4.10.0
  rxjs: ^7.8.2
  class-transformer: 0.5.1
  class-validator: 0.14.1
  reflect-metadata: 0.2.2
  typescript: ~5.9.3
  "@stablelib/ed25519": ^2.0.2
  # NOTE: keeping at zod 3 untwil we have updated oid4vc-ts to zod4 first
  # https://github.com/openwallet-foundation-labs/oid4vc-ts/issues/102
  zod: ^3.25.74
  nock: ^14.0.10
  express: ^5.1.0
  "@openwallet-foundation/askar-nodejs": ^0.4.2
  "@openwallet-foundation/askar-shared": ^0.4.2
  "@hyperledger/indy-vdr-nodejs": ^0.2.2
  "@hyperledger/indy-vdr-shared": ^0.2.2
  "@hyperledger/anoncreds-nodejs": ^0.3.3
  "@hyperledger/anoncreds-shared": ^0.3.3
  "@astronautlabs/jsonpath": ^1.1.2
  "@sphereon/pex-models": ^2.3.2
  "@animo-id/pex": ^6.1.1
  "@types/express": ^5.0.3
  "@types/ws": ^8.18.1
  ws: ^8.18.2
  vitest: ^3.2.4

ignoredBuiltDependencies:
  - es5-ext
  - esbuild
  - protobufjs
  - secp256k1

onlyBuiltDependencies:
  - "@2060.io/ffi-napi"
  - "@2060.io/ref-napi"
  - "@biomejs/biome"
  - "@hyperledger/anoncreds-nodejs"
  - "@hyperledger/indy-vdr-nodejs"
  - "@openwallet-foundation/askar-nodejs"
  - zstd-napi
  - cbor-extract
