export * from './credential-definition-private-record/postgres'
export * from './credential-definition-record/postgres'
export * from './credential-record/postgres'
export * from './key-correctness-proof-record/postgres'
export * from './link-secret-record/postgres'
export * from './revocation-registry-definition-private-record/postgres'
export * from './revocation-registry-definition-record/postgres'
export * from './schema-record/postgres'
