FROM python:3.6
WORKDIR /usr/src/app/
RUN pip3 install --no-cache-dir poetry

# Add docker-compose-wait tool
ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

COPY acapy-backchannel acapy-backchannel
COPY tests/* tests/
COPY pyproject.toml .
COPY poetry.lock .
RUN poetry install --no-dev

ENTRYPOINT ["/bin/sh", "-c", "/wait && poetry run pytest \"$@\"", "--"]
