name: Setup libSSL
description: Install libssl and libssl-dev 1.1
author: 'gentilester@gmail.com'

runs:
  using: composite
  steps:
    - name: Install libssl1.1
      run: |
        curl http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.21_amd64.deb -o libssl1.1.deb
        sudo dpkg -i libssl1.1.deb
      shell: bash

    - name: Instal libssl-dev.1.1
      run: |
        curl http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-dev_1.1.1-1ubuntu2.1~18.04.21_amd64.deb -o libssl-dev1.1.deb
        sudo dpkg -i libssl-dev1.1.deb
      shell: bash

branding:
  icon: scissors
  color: purple
