export * from './service'
export * from './verificationMethod'
export * from './DidDocument'
export * from './DidDocumentBuilder'
export * from './DidDocumentRole'
export * from './DidRegistrar'
export * from './DidResolver'
export * from './key-type'
export { parseDid } from './parse'
export { getKmsKeyIdForVerifiacationMethod } from './didDocumentKey'
