export const CHACHAPOLY_KEY_LEN = 32
export const CHACHAPOLY_NONCE_LEN = 12
export const CHACHAPOLY_TAG_LEN = 16
export const ENCRYPTED_KEY_LEN = CHACHAPOLY_NONCE_LEN + CHACHAPOLY_KEY_LEN + CHACHAPOLY_TAG_LEN
