export * from './types'
export * from './domain'
export * from './DidsModule'
export * from './DidEvents'
export * from './services'
export * from './repository'
export { DidKey } from './methods/key/DidKey'
export { PeerDid } from './methods/peer/PeerDid'
export { PeerDidNumAlgo } from './methods/peer/utils'
