export * from './DifPresentationExchangeError'
export * from './DifPresentationExchangeModule'
export * from './DifPresentationExchangeService'
export * from './models'
export { extractPresentationsWithDescriptorsFromSubmission } from './utils'
export type { DifPexPresentationWithDescriptor } from './utils'
