/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AttachmentDef {
    /**
    * Attachment identifier
    */
    'id'?: string;
    /**
    * Attachment type
    */
    'type'?: AttachmentDefTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "AttachmentDefTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AttachmentDef.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type AttachmentDefTypeEnum = "credential-offer" | "present-proof" ;

