/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AttachDecoratorDataJWS } from './AttachDecoratorDataJWS';
import { HttpFile } from '../http/http';

export class AttachDecoratorData {
    /**
    * Base64-encoded data
    */
    'base64'?: string;
    /**
    * JSON-serialized data
    */
    'json'?: any;
    /**
    * Detached Java Web Signature
    */
    'jws'?: AttachDecoratorDataJWS;
    /**
    * List of hypertext links to data
    */
    'links'?: Array<string>;
    /**
    * SHA256 hash (binhex encoded) of content
    */
    'sha256'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "base64",
            "baseName": "base64",
            "type": "string",
            "format": ""
        },
        {
            "name": "json",
            "baseName": "json",
            "type": "any",
            "format": ""
        },
        {
            "name": "jws",
            "baseName": "jws",
            "type": "AttachDecoratorDataJWS",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "sha256",
            "baseName": "sha256",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AttachDecoratorData.attributeTypeMap;
    }
    
    public constructor() {
    }
}

