/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AttachDecoratorData } from './AttachDecoratorData';
import { HttpFile } from '../http/http';

export class AttachDecorator {
    /**
    * Attachment identifier
    */
    'id'?: string;
    /**
    * Byte count of data included by reference
    */
    'byteCount'?: number;
    'data': AttachDecoratorData;
    /**
    * Human-readable description of content
    */
    'description'?: string;
    /**
    * File name
    */
    'filename'?: string;
    /**
    * Hint regarding last modification datetime, in ISO-8601 format
    */
    'lastmodTime'?: string;
    /**
    * MIME type
    */
    'mimeType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "@id",
            "type": "string",
            "format": ""
        },
        {
            "name": "byteCount",
            "baseName": "byte_count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "AttachDecoratorData",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "filename",
            "baseName": "filename",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastmodTime",
            "baseName": "lastmod_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "mimeType",
            "baseName": "mime-type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AttachDecorator.attributeTypeMap;
    }
    
    public constructor() {
    }
}

