/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ConnRecord {
    /**
    * Connection acceptance: manual or auto
    */
    'accept'?: ConnRecordAcceptEnum;
    /**
    * Optional alias to apply to connection for later use
    */
    'alias'?: string;
    /**
    * Connection identifier
    */
    'connectionId': string;
    /**
    * Time of record creation
    */
    'createdAt'?: string;
    /**
    * Error message
    */
    'errorMsg'?: string;
    /**
    * Inbound routing connection id to use
    */
    'inboundConnectionId'?: string;
    /**
    * Public key for connection
    */
    'invitationKey'?: string;
    /**
    * Invitation mode
    */
    'invitationMode'?: ConnRecordInvitationModeEnum;
    /**
    * ID of out-of-band invitation message
    */
    'invitationMsgId'?: string;
    /**
    * Our DID for connection
    */
    'myDid'?: string;
    /**
    * Connection request identifier
    */
    'requestId'?: string;
    /**
    * State per RFC 23
    */
    'rfc23State'?: string;
    /**
    * Routing state of connection
    */
    'routingState'?: ConnRecordRoutingStateEnum;
    /**
    * Current record state
    */
    'state': string;
    /**
    * Their DID for connection
    */
    'theirDid'?: string;
    /**
    * Their label for connection
    */
    'theirLabel'?: string;
    /**
    * Other agent's public DID for connection
    */
    'theirPublicDid'?: string;
    /**
    * Their role in the connection protocol
    */
    'theirRole'?: ConnRecordTheirRoleEnum;
    /**
    * Time of last record update
    */
    'updatedAt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accept",
            "baseName": "accept",
            "type": "ConnRecordAcceptEnum",
            "format": ""
        },
        {
            "name": "alias",
            "baseName": "alias",
            "type": "string",
            "format": ""
        },
        {
            "name": "connectionId",
            "baseName": "connection_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "errorMsg",
            "baseName": "error_msg",
            "type": "string",
            "format": ""
        },
        {
            "name": "inboundConnectionId",
            "baseName": "inbound_connection_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "invitationKey",
            "baseName": "invitation_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "invitationMode",
            "baseName": "invitation_mode",
            "type": "ConnRecordInvitationModeEnum",
            "format": ""
        },
        {
            "name": "invitationMsgId",
            "baseName": "invitation_msg_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "myDid",
            "baseName": "my_did",
            "type": "string",
            "format": ""
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "rfc23State",
            "baseName": "rfc23_state",
            "type": "string",
            "format": ""
        },
        {
            "name": "routingState",
            "baseName": "routing_state",
            "type": "ConnRecordRoutingStateEnum",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string",
            "format": ""
        },
        {
            "name": "theirDid",
            "baseName": "their_did",
            "type": "string",
            "format": ""
        },
        {
            "name": "theirLabel",
            "baseName": "their_label",
            "type": "string",
            "format": ""
        },
        {
            "name": "theirPublicDid",
            "baseName": "their_public_did",
            "type": "string",
            "format": ""
        },
        {
            "name": "theirRole",
            "baseName": "their_role",
            "type": "ConnRecordTheirRoleEnum",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConnRecord.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type ConnRecordAcceptEnum = "manual" | "auto" ;
export type ConnRecordInvitationModeEnum = "once" | "multi" | "static" ;
export type ConnRecordRoutingStateEnum = "none" | "request" | "active" | "error" ;
export type ConnRecordTheirRoleEnum = "invitee" | "requester" | "inviter" | "responder" ;

