/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConnRecord } from './ConnRecord';
import { HttpFile } from '../http/http';

export class ConnectionStaticResult {
    /**
    * My verification key
    */
    'myVerkey': string;
    /**
    * Local DID
    */
    'myDid': string;
    /**
    * My URL endpoint
    */
    'myEndpoint': string;
    'record': ConnRecord;
    /**
    * Remote DID
    */
    'theirDid': string;
    /**
    * Remote verification key
    */
    'theirVerkey': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "myVerkey",
            "baseName": "my_verkey",
            "type": "string",
            "format": ""
        },
        {
            "name": "myDid",
            "baseName": "my_did",
            "type": "string",
            "format": ""
        },
        {
            "name": "myEndpoint",
            "baseName": "my_endpoint",
            "type": "string",
            "format": ""
        },
        {
            "name": "record",
            "baseName": "record",
            "type": "ConnRecord",
            "format": ""
        },
        {
            "name": "theirDid",
            "baseName": "their_did",
            "type": "string",
            "format": ""
        },
        {
            "name": "theirVerkey",
            "baseName": "their_verkey",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConnectionStaticResult.attributeTypeMap;
    }
    
    public constructor() {
    }
}

