/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ConnectionStaticRequest {
    /**
    * Alias to assign to this connection
    */
    'alias'?: string;
    /**
    * Local DID
    */
    'myDid'?: string;
    /**
    * Seed to use for the local DID
    */
    'mySeed'?: string;
    /**
    * Remote DID
    */
    'theirDid'?: string;
    /**
    * URL endpoint for other party
    */
    'theirEndpoint'?: string;
    /**
    * Other party's label for this connection
    */
    'theirLabel'?: string;
    /**
    * Seed to use for the remote DID
    */
    'theirSeed'?: string;
    /**
    * Remote verification key
    */
    'theirVerkey'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "alias",
            "baseName": "alias",
            "type": "string",
            "format": ""
        },
        {
            "name": "myDid",
            "baseName": "my_did",
            "type": "string",
            "format": ""
        },
        {
            "name": "mySeed",
            "baseName": "my_seed",
            "type": "string",
            "format": ""
        },
        {
            "name": "theirDid",
            "baseName": "their_did",
            "type": "string",
            "format": ""
        },
        {
            "name": "theirEndpoint",
            "baseName": "their_endpoint",
            "type": "string",
            "format": ""
        },
        {
            "name": "theirLabel",
            "baseName": "their_label",
            "type": "string",
            "format": ""
        },
        {
            "name": "theirSeed",
            "baseName": "their_seed",
            "type": "string",
            "format": ""
        },
        {
            "name": "theirVerkey",
            "baseName": "their_verkey",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConnectionStaticRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}

