/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateInvitationRequest {
    /**
    * Identifier for active mediation record to be used
    */
    'mediationId'?: string;
    /**
    * Optional metadata to attach to the connection created with the invitation
    */
    'metadata'?: any;
    /**
    * List of recipient keys
    */
    'recipientKeys'?: Array<string>;
    /**
    * List of routing keys
    */
    'routingKeys'?: Array<string>;
    /**
    * Connection endpoint
    */
    'serviceEndpoint'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mediationId",
            "baseName": "mediation_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "recipientKeys",
            "baseName": "recipient_keys",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "routingKeys",
            "baseName": "routing_keys",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "serviceEndpoint",
            "baseName": "service_endpoint",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateInvitationRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}

