/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CredentialDefinitionSendRequest {
    /**
    * Revocation registry size
    */
    'revocationRegistrySize'?: number;
    /**
    * Schema identifier
    */
    'schemaId'?: string;
    /**
    * Revocation supported flag
    */
    'supportRevocation'?: boolean;
    /**
    * Credential definition identifier tag
    */
    'tag'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "revocationRegistrySize",
            "baseName": "revocation_registry_size",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "schemaId",
            "baseName": "schema_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "supportRevocation",
            "baseName": "support_revocation",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "tag",
            "baseName": "tag",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CredentialDefinitionSendRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}

