/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CredBrief {
    /**
    * Attribute names mapped to their raw values
    */
    'attrs'?: { [key: string]: string; };
    /**
    * Credential definition identifier
    */
    'credDefId'?: string;
    /**
    * Credential revocation identifier
    */
    'credRevId'?: string;
    /**
    * Credential referent
    */
    'referent'?: string;
    /**
    * Revocation registry identifier
    */
    'revRegId'?: string;
    /**
    * Schema identifier
    */
    'schemaId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "attrs",
            "baseName": "attrs",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "credDefId",
            "baseName": "cred_def_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "credRevId",
            "baseName": "cred_rev_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "referent",
            "baseName": "referent",
            "type": "string",
            "format": ""
        },
        {
            "name": "revRegId",
            "baseName": "rev_reg_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "schemaId",
            "baseName": "schema_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CredBrief.attributeTypeMap;
    }
    
    public constructor() {
    }
}

