/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CredentialDefinition {
    /**
    * Credential definition identifier
    */
    'id'?: string;
    /**
    * Schema identifier within credential definition identifier
    */
    'schemaId'?: string;
    /**
    * Tag within credential definition identifier
    */
    'tag'?: string;
    /**
    * Signature type: CL for Camenisch-Lysyanskaya
    */
    'type'?: any;
    /**
    * Credential definition primary and revocation values
    */
    'value'?: any;
    /**
    * Node protocol version
    */
    'ver'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "schemaId",
            "baseName": "schemaId",
            "type": "string",
            "format": ""
        },
        {
            "name": "tag",
            "baseName": "tag",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "any",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "any",
            "format": ""
        },
        {
            "name": "ver",
            "baseName": "ver",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CredentialDefinition.attributeTypeMap;
    }
    
    public constructor() {
    }
}

