/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CredAttrSpec } from './CredAttrSpec';
import { HttpFile } from '../http/http';

export class CredentialPreview {
    /**
    * Message type identifier
    */
    'type'?: string;
    'attributes': Array<CredAttrSpec>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "Array<CredAttrSpec>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CredentialPreview.attributeTypeMap;
    }
    
    public constructor() {
    }
}

