/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DIDEndpointWithType {
    /**
    * DID of interest
    */
    'did': string;
    /**
    * Endpoint to set (omit to delete)
    */
    'endpoint'?: string;
    /**
    * Endpoint type to set (default 'Endpoint'); affects only public or posted DIDs
    */
    'endpointType'?: DIDEndpointWithTypeEndpointTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "did",
            "baseName": "did",
            "type": "string",
            "format": ""
        },
        {
            "name": "endpoint",
            "baseName": "endpoint",
            "type": "string",
            "format": ""
        },
        {
            "name": "endpointType",
            "baseName": "endpoint_type",
            "type": "DIDEndpointWithTypeEndpointTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DIDEndpointWithType.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type DIDEndpointWithTypeEndpointTypeEnum = "Endpoint" | "Profile" | "LinkedDomains" ;

