/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class EndpointsResult {
    /**
    * My endpoint
    */
    'myEndpoint'?: string;
    /**
    * Their endpoint
    */
    'theirEndpoint'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "myEndpoint",
            "baseName": "my_endpoint",
            "type": "string",
            "format": ""
        },
        {
            "name": "theirEndpoint",
            "baseName": "their_endpoint",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EndpointsResult.attributeTypeMap;
    }
    
    public constructor() {
    }
}

