/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class IndyProofReqPredSpecRestrictions {
    /**
    * Credential definition identifier
    */
    'credDefId'?: string;
    /**
    * Credential issuer DID
    */
    'issuerDid'?: string;
    /**
    * Schema identifier
    */
    'schemaId'?: string;
    /**
    * Schema issuer (origin) DID
    */
    'schemaIssuerDid'?: string;
    /**
    * Schema name
    */
    'schemaName'?: string;
    /**
    * Schema version
    */
    'schemaVersion'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "credDefId",
            "baseName": "cred_def_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "issuerDid",
            "baseName": "issuer_did",
            "type": "string",
            "format": ""
        },
        {
            "name": "schemaId",
            "baseName": "schema_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "schemaIssuerDid",
            "baseName": "schema_issuer_did",
            "type": "string",
            "format": ""
        },
        {
            "name": "schemaName",
            "baseName": "schema_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "schemaVersion",
            "baseName": "schema_version",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IndyProofReqPredSpecRestrictions.attributeTypeMap;
    }
    
    public constructor() {
    }
}

