/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class IndyCredInfo {
    /**
    * Attribute names and value
    */
    'attrs'?: { [key: string]: string; };
    /**
    * Wallet referent
    */
    'referent'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "attrs",
            "baseName": "attrs",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "referent",
            "baseName": "referent",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IndyCredInfo.attributeTypeMap;
    }
    
    public constructor() {
    }
}

