/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class IndyRequestedCredsRequestedAttr {
    /**
    * Wallet credential identifier (typically but not necessarily a UUID)
    */
    'credId': string;
    /**
    * Whether to reveal attribute in proof (default true)
    */
    'revealed'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "credId",
            "baseName": "cred_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "revealed",
            "baseName": "revealed",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IndyRequestedCredsRequestedAttr.attributeTypeMap;
    }
    
    public constructor() {
    }
}

