/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IndyProofReqAttrSpec } from './IndyProofReqAttrSpec';
import { IndyProofReqNonRevoked } from './IndyProofReqNonRevoked';
import { IndyProofReqPredSpec } from './IndyProofReqPredSpec';
import { HttpFile } from '../http/http';

export class IndyProofRequest {
    /**
    * Proof request name
    */
    'name': string;
    'nonRevoked'?: IndyProofReqNonRevoked;
    /**
    * Nonce
    */
    'nonce'?: string;
    /**
    * Requested attribute specifications of proof request
    */
    'requestedAttributes': { [key: string]: IndyProofReqAttrSpec; };
    /**
    * Requested predicate specifications of proof request
    */
    'requestedPredicates': { [key: string]: IndyProofReqPredSpec; };
    /**
    * Proof request version
    */
    'version': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "nonRevoked",
            "baseName": "non_revoked",
            "type": "IndyProofReqNonRevoked",
            "format": ""
        },
        {
            "name": "nonce",
            "baseName": "nonce",
            "type": "string",
            "format": ""
        },
        {
            "name": "requestedAttributes",
            "baseName": "requested_attributes",
            "type": "{ [key: string]: IndyProofReqAttrSpec; }",
            "format": ""
        },
        {
            "name": "requestedPredicates",
            "baseName": "requested_predicates",
            "type": "{ [key: string]: IndyProofReqPredSpec; }",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IndyProofRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}

