/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IndyCredInfo } from './IndyCredInfo';
import { IndyProofReqNonRevoked } from './IndyProofReqNonRevoked';
import { HttpFile } from '../http/http';

export class IndyCredPrecis {
    /**
    * Credential definition identifier
    */
    'credDefId'?: string;
    /**
    * Credential info
    */
    'credInfo'?: IndyCredInfo;
    /**
    * Credential revocation identifier
    */
    'credRev'?: string;
    /**
    * Non-revocation interval from presentation request
    */
    'interval'?: IndyProofReqNonRevoked;
    'presentationReferents'?: Array<string>;
    /**
    * Revocation registry identifier
    */
    'revRegId'?: string;
    /**
    * Schema identifier
    */
    'schemaId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "credDefId",
            "baseName": "cred_def_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "credInfo",
            "baseName": "cred_info",
            "type": "IndyCredInfo",
            "format": ""
        },
        {
            "name": "credRev",
            "baseName": "cred_rev",
            "type": "string",
            "format": ""
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "IndyProofReqNonRevoked",
            "format": ""
        },
        {
            "name": "presentationReferents",
            "baseName": "presentation_referents",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "revRegId",
            "baseName": "rev_reg_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "schemaId",
            "baseName": "schema_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IndyCredPrecis.attributeTypeMap;
    }
    
    public constructor() {
    }
}

