/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IndyProofReqNonRevoked } from './IndyProofReqNonRevoked';
import { IndyProofReqPredSpecRestrictions } from './IndyProofReqPredSpecRestrictions';
import { HttpFile } from '../http/http';

export class IndyProofReqPredSpec {
    /**
    * Attribute name
    */
    'name': string;
    'nonRevoked'?: IndyProofReqNonRevoked;
    /**
    * Predicate type ('<', '<=', '>=', or '>')
    */
    'pType': IndyProofReqPredSpecPTypeEnum;
    /**
    * Threshold value
    */
    'pValue': number;
    /**
    * If present, credential must satisfy one of given restrictions
    */
    'restrictions'?: Array<IndyProofReqPredSpecRestrictions>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "nonRevoked",
            "baseName": "non_revoked",
            "type": "IndyProofReqNonRevoked",
            "format": ""
        },
        {
            "name": "pType",
            "baseName": "p_type",
            "type": "IndyProofReqPredSpecPTypeEnum",
            "format": ""
        },
        {
            "name": "pValue",
            "baseName": "p_value",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "restrictions",
            "baseName": "restrictions",
            "type": "Array<IndyProofReqPredSpecRestrictions>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IndyProofReqPredSpec.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type IndyProofReqPredSpecPTypeEnum = "&lt;" | "&lt;&#x3D;" | "&gt;&#x3D;" | "&gt;" ;

