/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IndyProofReqNonRevoked } from './IndyProofReqNonRevoked';
import { HttpFile } from '../http/http';

export class IndyProofReqAttrSpec {
    /**
    * Attribute name
    */
    'name'?: string;
    /**
    * Attribute name group
    */
    'names'?: Array<string>;
    'nonRevoked'?: IndyProofReqNonRevoked;
    /**
    * If present, credential must satisfy one of given restrictions: specify schema_id, schema_issuer_did, schema_name, schema_version, issuer_did, cred_def_id, and/or attr::<attribute-name>::value where <attribute-name> represents a credential attribute name
    */
    'restrictions'?: Array<{ [key: string]: string; }>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "names",
            "baseName": "names",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "nonRevoked",
            "baseName": "non_revoked",
            "type": "IndyProofReqNonRevoked",
            "format": ""
        },
        {
            "name": "restrictions",
            "baseName": "restrictions",
            "type": "Array<{ [key: string]: string; }>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IndyProofReqAttrSpec.attributeTypeMap;
    }
    
    public constructor() {
    }
}

