/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AttachDecorator } from './AttachDecorator';
import { Service } from './Service';
import { HttpFile } from '../http/http';

export class InvitationReceiveRequest {
    /**
    * Message identifier
    */
    'id'?: string;
    /**
    * Message type
    */
    'type'?: string;
    'handshakeProtocols'?: Array<string>;
    /**
    * Optional label
    */
    'label'?: string;
    /**
    * Optional request attachment
    */
    'requestattach'?: Array<AttachDecorator>;
    'service'?: any;
    'serviceBlocks'?: Array<Service>;
    'serviceDids'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "@id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "handshakeProtocols",
            "baseName": "handshake_protocols",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "requestattach",
            "baseName": "request~attach",
            "type": "Array<AttachDecorator>",
            "format": ""
        },
        {
            "name": "service",
            "baseName": "service",
            "type": "any",
            "format": ""
        },
        {
            "name": "serviceBlocks",
            "baseName": "service_blocks",
            "type": "Array<Service>",
            "format": ""
        },
        {
            "name": "serviceDids",
            "baseName": "service_dids",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InvitationReceiveRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}

