/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AttachmentDef } from './AttachmentDef';
import { HttpFile } from '../http/http';

export class InvitationCreateRequest {
    /**
    * Alias for connection
    */
    'alias'?: string;
    /**
    * Optional invitation attachments
    */
    'attachments'?: Array<AttachmentDef>;
    'handshakeProtocols'?: Array<string>;
    /**
    * Identifier for active mediation record to be used
    */
    'mediationId'?: string;
    /**
    * Optional metadata to attach to the connection created with the invitation
    */
    'metadata'?: any;
    /**
    * Label for connection invitation
    */
    'myLabel'?: string;
    /**
    * Whether to use public DID in invitation
    */
    'usePublicDid'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "alias",
            "baseName": "alias",
            "type": "string",
            "format": ""
        },
        {
            "name": "attachments",
            "baseName": "attachments",
            "type": "Array<AttachmentDef>",
            "format": ""
        },
        {
            "name": "handshakeProtocols",
            "baseName": "handshake_protocols",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "mediationId",
            "baseName": "mediation_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "myLabel",
            "baseName": "my_label",
            "type": "string",
            "format": ""
        },
        {
            "name": "usePublicDid",
            "baseName": "use_public_did",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InvitationCreateRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}

