/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConnectionInvitation } from './ConnectionInvitation';
import { HttpFile } from '../http/http';

export class InvitationResult {
    /**
    * Connection identifier
    */
    'connectionId': string;
    'invitation': ConnectionInvitation;
    /**
    * Invitation URL
    */
    'invitationUrl': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "connectionId",
            "baseName": "connection_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "invitation",
            "baseName": "invitation",
            "type": "ConnectionInvitation",
            "format": ""
        },
        {
            "name": "invitationUrl",
            "baseName": "invitation_url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InvitationResult.attributeTypeMap;
    }
    
    public constructor() {
    }
}

