/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KeylistQueryPaginate } from './KeylistQueryPaginate';
import { HttpFile } from '../http/http';

export class KeylistQuery {
    /**
    * Message identifier
    */
    'id'?: string;
    /**
    * Message type
    */
    'type'?: string;
    /**
    * Query dictionary object
    */
    'filter'?: any;
    /**
    * Pagination info
    */
    'paginate'?: KeylistQueryPaginate;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "@id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "any",
            "format": ""
        },
        {
            "name": "paginate",
            "baseName": "paginate",
            "type": "KeylistQueryPaginate",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return KeylistQuery.attributeTypeMap;
    }
    
    public constructor() {
    }
}

