/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KeylistUpdateRule } from './KeylistUpdateRule';
import { HttpFile } from '../http/http';

export class KeylistUpdate {
    /**
    * Message identifier
    */
    'id'?: string;
    /**
    * Message type
    */
    'type'?: string;
    /**
    * List of update rules
    */
    'updates'?: Array<KeylistUpdateRule>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "@id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "updates",
            "baseName": "updates",
            "type": "Array<KeylistUpdateRule>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return KeylistUpdate.attributeTypeMap;
    }
    
    public constructor() {
    }
}

