/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MediationRecord } from './MediationRecord';
import { HttpFile } from '../http/http';

export class MediationList {
    /**
    * List of mediation records
    */
    'results'?: Array<MediationRecord>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<MediationRecord>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MediationList.attributeTypeMap;
    }
    
    public constructor() {
    }
}

