/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MediationRecord {
    'connectionId': string;
    /**
    * Time of record creation
    */
    'createdAt'?: string;
    'endpoint'?: string;
    'mediationId'?: string;
    'mediatorTerms'?: Array<string>;
    'recipientTerms'?: Array<string>;
    'role': string;
    'routingKeys'?: Array<string>;
    /**
    * Current record state
    */
    'state'?: string;
    /**
    * Time of last record update
    */
    'updatedAt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "connectionId",
            "baseName": "connection_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "endpoint",
            "baseName": "endpoint",
            "type": "string",
            "format": ""
        },
        {
            "name": "mediationId",
            "baseName": "mediation_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "mediatorTerms",
            "baseName": "mediator_terms",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "recipientTerms",
            "baseName": "recipient_terms",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "string",
            "format": ""
        },
        {
            "name": "routingKeys",
            "baseName": "routing_keys",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MediationRecord.attributeTypeMap;
    }
    
    public constructor() {
    }
}

