/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MenuFormParam } from './MenuFormParam';
import { HttpFile } from '../http/http';

export class MenuForm {
    /**
    * Additional descriptive text for menu form
    */
    'description'?: string;
    /**
    * List of form parameters
    */
    'params'?: Array<MenuFormParam>;
    /**
    * Alternative label for form submit button
    */
    'submitLabel'?: string;
    /**
    * Menu form title
    */
    'title'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "params",
            "baseName": "params",
            "type": "Array<MenuFormParam>",
            "format": ""
        },
        {
            "name": "submitLabel",
            "baseName": "submit-label",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MenuForm.attributeTypeMap;
    }
    
    public constructor() {
    }
}

