/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MenuOption } from './MenuOption';
import { HttpFile } from '../http/http';

export class MenuJson {
    /**
    * Introductory text for the menu
    */
    'description'?: string;
    /**
    * Optional error message to display in menu header
    */
    'errormsg'?: string;
    /**
    * List of menu options
    */
    'options': Array<MenuOption>;
    /**
    * Menu title
    */
    'title'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "errormsg",
            "baseName": "errormsg",
            "type": "string",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "Array<MenuOption>",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MenuJson.attributeTypeMap;
    }
    
    public constructor() {
    }
}

