/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PresPredSpec {
    /**
    * Credential definition identifier
    */
    'credDefId'?: string;
    /**
    * Attribute name
    */
    'name': string;
    /**
    * Predicate type ('<', '<=', '>=', or '>')
    */
    'predicate': PresPredSpecPredicateEnum;
    /**
    * Threshold value
    */
    'threshold': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "credDefId",
            "baseName": "cred_def_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "predicate",
            "baseName": "predicate",
            "type": "PresPredSpecPredicateEnum",
            "format": ""
        },
        {
            "name": "threshold",
            "baseName": "threshold",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return PresPredSpec.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type PresPredSpecPredicateEnum = "&lt;" | "&lt;&#x3D;" | "&gt;&#x3D;" | "&gt;" ;

