/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RevokeRequest {
    /**
    * Credential exchange identifier
    */
    'credExId'?: string;
    /**
    * Credential revocation identifier
    */
    'credRevId'?: string;
    /**
    * (True) publish revocation to ledger immediately, or (default, False) mark it pending
    */
    'publish'?: boolean;
    /**
    * Revocation registry identifier
    */
    'revRegId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "credExId",
            "baseName": "cred_ex_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "credRevId",
            "baseName": "cred_rev_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "publish",
            "baseName": "publish",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "revRegId",
            "baseName": "rev_reg_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RevokeRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}

