/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RevRegCreateRequest {
    /**
    * Credential definition identifier
    */
    'credentialDefinitionId'?: string;
    /**
    * Revocation registry size
    */
    'maxCredNum'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "credentialDefinitionId",
            "baseName": "credential_definition_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "maxCredNum",
            "baseName": "max_cred_num",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return RevRegCreateRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}

