/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RevRegUpdateTailsFileUri {
    /**
    * Public URI to the tails file
    */
    'tailsPublicUri': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tailsPublicUri",
            "baseName": "tails_public_uri",
            "type": "string",
            "format": "url"
        }    ];

    static getAttributeTypeMap() {
        return RevRegUpdateTailsFileUri.attributeTypeMap;
    }
    
    public constructor() {
    }
}

