/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Schema {
    /**
    * Schema attribute names
    */
    'attrNames'?: Array<string>;
    /**
    * Schema identifier
    */
    'id'?: string;
    /**
    * Schema name
    */
    'name'?: string;
    /**
    * Schema sequence number
    */
    'seqNo'?: number;
    /**
    * Node protocol version
    */
    'ver'?: string;
    /**
    * Schema version
    */
    'version'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "attrNames",
            "baseName": "attrNames",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "seqNo",
            "baseName": "seqNo",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "ver",
            "baseName": "ver",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Schema.attributeTypeMap;
    }
    
    public constructor() {
    }
}

