/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MenuJson } from './MenuJson';
import { HttpFile } from '../http/http';

export class SendMenu {
    /**
    * Menu to send to connection
    */
    'menu': MenuJson;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "menu",
            "baseName": "menu",
            "type": "MenuJson",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendMenu.attributeTypeMap;
    }
    
    public constructor() {
    }
}

