/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AMLRecord } from './AMLRecord';
import { TAAAcceptance } from './TAAAcceptance';
import { TAARecord } from './TAARecord';
import { HttpFile } from '../http/http';

export class TAAInfo {
    'amlRecord': AMLRecord;
    'taaAccepted': TAAAcceptance;
    'taaRecord': TAARecord;
    'taaRequired': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amlRecord",
            "baseName": "aml_record",
            "type": "AMLRecord",
            "format": ""
        },
        {
            "name": "taaAccepted",
            "baseName": "taa_accepted",
            "type": "TAAAcceptance",
            "format": ""
        },
        {
            "name": "taaRecord",
            "baseName": "taa_record",
            "type": "TAARecord",
            "format": ""
        },
        {
            "name": "taaRequired",
            "baseName": "taa_required",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TAAInfo.attributeTypeMap;
    }
    
    public constructor() {
    }
}

