/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V10CredentialExchange } from './V10CredentialExchange';
import { HttpFile } from '../http/http';

export class V10CredentialExchangeListResult {
    /**
    * Aries#0036 v1.0 credential exchange records
    */
    'results'?: Array<V10CredentialExchange>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<V10CredentialExchange>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V10CredentialExchangeListResult.attributeTypeMap;
    }
    
    public constructor() {
    }
}

