/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CredentialPreview } from './CredentialPreview';
import { HttpFile } from '../http/http';

export class V10CredentialProposalRequestMand {
    /**
    * Whether to remove the credential exchange record on completion (overrides --preserve-exchange-records configuration setting)
    */
    'autoRemove'?: boolean;
    /**
    * Human-readable comment
    */
    'comment'?: string;
    /**
    * Connection identifier
    */
    'connectionId': string;
    /**
    * Credential definition identifier
    */
    'credDefId'?: string;
    'credentialProposal': CredentialPreview;
    /**
    * Credential issuer DID
    */
    'issuerDid'?: string;
    /**
    * Schema identifier
    */
    'schemaId'?: string;
    /**
    * Schema issuer DID
    */
    'schemaIssuerDid'?: string;
    /**
    * Schema name
    */
    'schemaName'?: string;
    /**
    * Schema version
    */
    'schemaVersion'?: string;
    /**
    * Whether to trace event (default false)
    */
    'trace'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "autoRemove",
            "baseName": "auto_remove",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string",
            "format": ""
        },
        {
            "name": "connectionId",
            "baseName": "connection_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "credDefId",
            "baseName": "cred_def_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "credentialProposal",
            "baseName": "credential_proposal",
            "type": "CredentialPreview",
            "format": ""
        },
        {
            "name": "issuerDid",
            "baseName": "issuer_did",
            "type": "string",
            "format": ""
        },
        {
            "name": "schemaId",
            "baseName": "schema_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "schemaIssuerDid",
            "baseName": "schema_issuer_did",
            "type": "string",
            "format": ""
        },
        {
            "name": "schemaName",
            "baseName": "schema_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "schemaVersion",
            "baseName": "schema_version",
            "type": "string",
            "format": ""
        },
        {
            "name": "trace",
            "baseName": "trace",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V10CredentialProposalRequestMand.attributeTypeMap;
    }
    
    public constructor() {
    }
}

