/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PresentationPreview } from './PresentationPreview';
import { HttpFile } from '../http/http';

export class V10PresentationProposalRequest {
    /**
    * Whether to respond automatically to presentation requests, building and presenting requested proof
    */
    'autoPresent'?: boolean;
    /**
    * Human-readable comment
    */
    'comment'?: string;
    /**
    * Connection identifier
    */
    'connectionId': string;
    'presentationProposal': PresentationPreview;
    /**
    * Whether to trace event (default false)
    */
    'trace'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "autoPresent",
            "baseName": "auto_present",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string",
            "format": ""
        },
        {
            "name": "connectionId",
            "baseName": "connection_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "presentationProposal",
            "baseName": "presentation_proposal",
            "type": "PresentationPreview",
            "format": ""
        },
        {
            "name": "trace",
            "baseName": "trace",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V10PresentationProposalRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}

