/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class V10PresentationExchange {
    /**
    * Prover choice to auto-present proof as verifier requests
    */
    'autoPresent'?: boolean;
    /**
    * Connection identifier
    */
    'connectionId'?: string;
    /**
    * Time of record creation
    */
    'createdAt'?: string;
    /**
    * Error message
    */
    'errorMsg'?: string;
    /**
    * Present-proof exchange initiator: self or external
    */
    'initiator'?: V10PresentationExchangeInitiatorEnum;
    /**
    * (Indy) presentation (also known as proof)
    */
    'presentation'?: any;
    /**
    * Presentation exchange identifier
    */
    'presentationExchangeId'?: string;
    /**
    * Serialized presentation proposal message
    */
    'presentationProposalDict'?: any;
    /**
    * (Indy) presentation request (also known as proof request)
    */
    'presentationRequest'?: any;
    /**
    * Serialized presentation request message
    */
    'presentationRequestDict'?: any;
    /**
    * Present-proof exchange role: prover or verifier
    */
    'role'?: V10PresentationExchangeRoleEnum;
    /**
    * Present-proof exchange state
    */
    'state'?: string;
    /**
    * Thread identifier
    */
    'threadId'?: string;
    /**
    * Record trace information, based on agent configuration
    */
    'trace'?: boolean;
    /**
    * Time of last record update
    */
    'updatedAt'?: string;
    /**
    * Whether presentation is verified: true or false
    */
    'verified'?: V10PresentationExchangeVerifiedEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "autoPresent",
            "baseName": "auto_present",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "connectionId",
            "baseName": "connection_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "errorMsg",
            "baseName": "error_msg",
            "type": "string",
            "format": ""
        },
        {
            "name": "initiator",
            "baseName": "initiator",
            "type": "V10PresentationExchangeInitiatorEnum",
            "format": ""
        },
        {
            "name": "presentation",
            "baseName": "presentation",
            "type": "any",
            "format": ""
        },
        {
            "name": "presentationExchangeId",
            "baseName": "presentation_exchange_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "presentationProposalDict",
            "baseName": "presentation_proposal_dict",
            "type": "any",
            "format": ""
        },
        {
            "name": "presentationRequest",
            "baseName": "presentation_request",
            "type": "any",
            "format": ""
        },
        {
            "name": "presentationRequestDict",
            "baseName": "presentation_request_dict",
            "type": "any",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "V10PresentationExchangeRoleEnum",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string",
            "format": ""
        },
        {
            "name": "threadId",
            "baseName": "thread_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "trace",
            "baseName": "trace",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "verified",
            "baseName": "verified",
            "type": "V10PresentationExchangeVerifiedEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V10PresentationExchange.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type V10PresentationExchangeInitiatorEnum = "self" | "external" ;
export type V10PresentationExchangeRoleEnum = "prover" | "verifier" ;
export type V10PresentationExchangeVerifiedEnum = "true" | "false" ;

