/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IndyRequestedCredsRequestedAttr } from './IndyRequestedCredsRequestedAttr';
import { IndyRequestedCredsRequestedPred } from './IndyRequestedCredsRequestedPred';
import { HttpFile } from '../http/http';

export class V10PresentationRequest {
    /**
    * Nested object mapping proof request attribute referents to requested-attribute specifiers
    */
    'requestedAttributes': { [key: string]: IndyRequestedCredsRequestedAttr; };
    /**
    * Nested object mapping proof request predicate referents to requested-predicate specifiers
    */
    'requestedPredicates': { [key: string]: IndyRequestedCredsRequestedPred; };
    /**
    * Self-attested attributes to build into proof
    */
    'selfAttestedAttributes': { [key: string]: string; };
    /**
    * Whether to trace event (default false)
    */
    'trace'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "requestedAttributes",
            "baseName": "requested_attributes",
            "type": "{ [key: string]: IndyRequestedCredsRequestedAttr; }",
            "format": ""
        },
        {
            "name": "requestedPredicates",
            "baseName": "requested_predicates",
            "type": "{ [key: string]: IndyRequestedCredsRequestedPred; }",
            "format": ""
        },
        {
            "name": "selfAttestedAttributes",
            "baseName": "self_attested_attributes",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "trace",
            "baseName": "trace",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V10PresentationRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}

