/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V20CredFilterDIF } from './V20CredFilterDIF';
import { V20CredFilterIndy } from './V20CredFilterIndy';
import { HttpFile } from '../http/http';

export class V20CredFilter {
    /**
    * Credential filter for DIF
    */
    'dif'?: V20CredFilterDIF;
    /**
    * Credential filter for indy
    */
    'indy'?: V20CredFilterIndy;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dif",
            "baseName": "dif",
            "type": "V20CredFilterDIF",
            "format": ""
        },
        {
            "name": "indy",
            "baseName": "indy",
            "type": "V20CredFilterIndy",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V20CredFilter.attributeTypeMap;
    }
    
    public constructor() {
    }
}

