/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class V20CredExRecordDIF {
    /**
    * Time of record creation
    */
    'createdAt'?: string;
    /**
    * Record identifier
    */
    'credExDifId'?: string;
    /**
    * Corresponding v2.0 credential exchange record identifier
    */
    'credExId'?: string;
    /**
    * DIF item
    */
    'item'?: any;
    /**
    * Current record state
    */
    'state'?: string;
    /**
    * Time of last record update
    */
    'updatedAt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "credExDifId",
            "baseName": "cred_ex_dif_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "credExId",
            "baseName": "cred_ex_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "item",
            "baseName": "item",
            "type": "any",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V20CredExRecordDIF.attributeTypeMap;
    }
    
    public constructor() {
    }
}

