/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class V20CredExRecordIndy {
    /**
    * Time of record creation
    */
    'createdAt'?: string;
    /**
    * Corresponding v2.0 credential exchange record identifier
    */
    'credExId'?: string;
    /**
    * Record identifier
    */
    'credExIndyId'?: string;
    /**
    * Credential request metadata for indy holder
    */
    'credRequestMetadata'?: any;
    /**
    * Credential revocation identifier within revocation registry
    */
    'credRevId'?: string;
    /**
    * Revocation registry identifier
    */
    'revRegId'?: string;
    /**
    * Current record state
    */
    'state'?: string;
    /**
    * Time of last record update
    */
    'updatedAt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "credExId",
            "baseName": "cred_ex_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "credExIndyId",
            "baseName": "cred_ex_indy_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "credRequestMetadata",
            "baseName": "cred_request_metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "credRevId",
            "baseName": "cred_rev_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "revRegId",
            "baseName": "rev_reg_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V20CredExRecordIndy.attributeTypeMap;
    }
    
    public constructor() {
    }
}

