/**
 * Aries Cloud Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V20CredExRecordDetail } from './V20CredExRecordDetail';
import { HttpFile } from '../http/http';

export class V20CredExRecordListResult {
    /**
    * Credential exchange records and corresponding detail records
    */
    'results'?: Array<V20CredExRecordDetail>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<V20CredExRecordDetail>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V20CredExRecordListResult.attributeTypeMap;
    }
    
    public constructor() {
    }
}

