export { DIDCommMessage } from './DIDCommMessage'
export { DIDCommV1Message } from './v1/DIDCommV1Message'
export { DIDCommV2Message } from './v2/DIDCommV2Message'
export { DIDCommV1BaseMessage } from './v1/DIDCommV1BaseMessage'
export { DIDCommV2BaseMessage, DIDCommV2MessageParams } from './v2/DIDCommV2BaseMessage'
export { EncryptedMessage } from './types'
