export * from '../formats/AnonCredsDidCommCredentialFormat'
export { AnonCredsDidCommCredentialFormatService } from '../formats/AnonCredsDidCommCredentialFormatService'
export * from '../formats/AnonCredsDidCommProofFormat'
export { AnonCredsDidCommProofFormatService } from '../formats/AnonCredsDidCommProofFormatService'
export { AnonCredsLinkSecretBindingProvider } from '../formats/AnonCredsLinkSecretBindingProvider'
export * from '../formats/LegacyIndyDidCommCredentialFormat'
export { LegacyIndyDidCommCredentialFormatService } from '../formats/LegacyIndyDidCommCredentialFormatService'
export * from '../formats/LegacyIndyDidCommProofFormat'
export { LegacyIndyDidCommProofFormatService } from '../formats/LegacyIndyDidCommProofFormatService'
export { migrateCredentialExchangeRecordToV0_4 } from '../updates/0.3.1-0.4/credentialExchangeRecord'
